from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ServerPool(Protocol):
    @property
    def urls(self) -> list[str]: ...
    def active(self) -> str: ...
    def report_success(self, url: str) -> None: ...
    def report_failure(self, url: str) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
